name: Merge Workflow

on:
  pull_request:
    branch: [main]
    types: [opened, reopened]

jobs:
  merge-feature-into-main:
    runs-on: ubuntu-latest
    needs: build-feature
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.base_url}}
          fetch-depth: 0
      - name: Set JDK_JAVA_OPTIONS
        run: echo "export JDK_JAVA_OPTIONS=\"-Djdk.attach.allowAttachSelf=true\"" >> $GITHUB_ENV
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '8'

          
      - name: VERSIONS
        run: |
          java -version
          mvn -v 
          
      
      - name: permisos evo master
        run: chmod +rx evomaster.jar

      - name: Build and test with JavaAgent
        run: |
           mvn clean compile exec:exec -X  | java -jar ./evomaster.jar
           
      - name: Run evomaster
        if: ${{ success() }}
        run:  java -jar ./evomaster.jar