name: Merge Workflow

on:
  pull_request:
    branch: [main]
    types: [opened, reopened]

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '8'
                
      - name: permisos evo master
        run: chmod +rx evomaster.jar

      - name: Build and test with JavaAgent
        run: |
           mvn clean compile exec:exec -X & 
           
           PID=$!

           sleep 10
           
      - name: Run Action 2
        id: run-migrated-script
        uses: alegonzalezz/evomaste_script@v1.0.2

      - name: show variables
      run: |
          echo "1) feedbackDirectedSampling: ${{ steps.run-migrated-script.outputs.feedbackDirectedSampling }}"
          echo "2) probOfApplySQLActionToCreateResources: ${{ steps.run-migrated-script.outputs.probOfApplySQLActionToCreateResources }}"
          echo "3) probOfRandomSampling: ${{ steps.run-migrated-script.outputs.probOfRandomSampling }}"
          echo "4) baseTaintAnalysisProbability: ${{ steps.run-migrated-script.outputs.baseTaintAnalysisProbability }}"
          echo "5) focusedSearchActivationTime: ${{ steps.run-migrated-script.outputs.focusedSearchActivationTime }}"
          echo "5) focusedSearchActivationTime: ${{ steps.run-migrated-script.outputs.focusedSearchActivationTime }}"

